package deep

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"

	"caseagent/internal/agent/prompts"

	"github.com/cloudwego/eino/adk"
	"github.com/cloudwego/eino/components/model"
	"github.com/cloudwego/eino/schema"
)

type Agent struct {
	chatModel model.BaseChatModel
	subAgents []adk.Agent
	prompts   *prompts.Registry
}

type Config struct {
	ChatModel model.BaseChatModel
	SubAgents []adk.Agent
	Prompts   *prompts.Registry
}

func New(ctx context.Context, cfg *Config) (*Agent, error) {
	if cfg.ChatModel == nil {
		return nil, fmt.Errorf("chat model is required")
	}
	registry := cfg.Prompts
	if registry == nil {
		registry = prompts.DefaultRegistry()
	}

	return &Agent{
		chatModel: cfg.ChatModel,
		subAgents: cfg.SubAgents,
		prompts:   registry,
	}, nil
}

// GenerateCases generates sectioned test cases by coordinating sub-agents.
func (a *Agent) GenerateCases(ctx context.Context, requirements string, knowledge string) (string, error) {
	if draft, ok := a.generateWithSubAgents(ctx, requirements, knowledge); ok {
		return a.RefineCases(ctx, requirements, knowledge, draft)
	}

	rendered, err := a.prompts.Render(prompts.DeepCases, prompts.CasePromptData{
		Requirements: requirements,
		Knowledge:    knowledge,
	})
	if err != nil {
		return "", err
	}

	messages := []*schema.Message{
		schema.UserMessage(rendered.Content),
	}

	result, err := a.chatModel.Generate(prompts.WithRenderedPrompt(ctx, rendered), messages)
	if err != nil {
		return "", fmt.Errorf("failed to generate test cases: %w", err)
	}

	return result.Content, nil
}

func (a *Agent) generateWithSubAgents(ctx context.Context, requirements string, knowledge string) (string, bool) {
	if len(a.subAgents) == 0 {
		return "", false
	}

	rawInput, err := json.Marshal(map[string]string{
		"requirements": requirements,
		"knowledge":    knowledge,
	})
	if err != nil {
		slog.Warn("DeepAgent failed to marshal sub-agent input", "error", err)
		return "", false
	}

	outputs := make([]json.RawMessage, 0, len(a.subAgents))
	for _, subAgent := range a.subAgents {
		if subAgent == nil {
			continue
		}
		output, err := runSubAgent(ctx, subAgent, string(rawInput))
		if err != nil {
			slog.Warn("DeepAgent sub-agent coordination failed",
				"agent", subAgent.Name(ctx), "error", err)
			continue
		}
		cleaned := extractJSONPayload(output)
		if cleaned == "" {
			continue
		}
		var sections []json.RawMessage
		if err := json.Unmarshal([]byte(cleaned), &sections); err != nil || len(sections) == 0 {
			slog.Warn("DeepAgent sub-agent output skipped",
				"agent", subAgent.Name(ctx), "parse_err", err)
			continue
		}
		outputs = append(outputs, sections...)
	}
	if len(outputs) == 0 {
		return "", false
	}
	rawDraft, err := json.Marshal(outputs)
	if err != nil {
		slog.Warn("DeepAgent failed to marshal sub-agent draft", "error", err)
		return "", false
	}
	return string(rawDraft), true
}

func runSubAgent(ctx context.Context, subAgent adk.Agent, inputJSON string) (string, error) {
	iterator := subAgent.Run(ctx, &adk.AgentInput{
		Messages: []adk.Message{schema.UserMessage(inputJSON)},
	})
	var output string
	for {
		event, ok := iterator.Next()
		if !ok {
			break
		}
		if event == nil {
			continue
		}
		if event.Err != nil {
			return "", event.Err
		}
		if event.Output == nil {
			continue
		}
		if text, ok := event.Output.CustomizedOutput.(string); ok && strings.TrimSpace(text) != "" {
			output = text
		}
		if event.Output.MessageOutput != nil {
			message, err := event.Output.MessageOutput.GetMessage()
			if err != nil {
				return "", err
			}
			if message != nil && strings.TrimSpace(message.Content) != "" {
				output = message.Content
			}
		}
	}
	if strings.TrimSpace(output) == "" {
		return "", fmt.Errorf("sub-agent %q produced no output", subAgent.Name(ctx))
	}
	return output, nil
}

// RefineCases consolidates draft sections generated by sub-agents.
func (a *Agent) RefineCases(ctx context.Context, requirements string, knowledge string, draftJSON string) (string, error) {
	draftJSON = strings.TrimSpace(draftJSON)
	if draftJSON == "" {
		return "", fmt.Errorf("empty draft sections")
	}

	rendered, err := a.prompts.Render(prompts.DeepRefineCases, prompts.CasePromptData{
		Requirements: requirements,
		Knowledge:    knowledge,
		DraftJSON:    draftJSON,
	})
	if err != nil {
		return "", err
	}

	messages := []*schema.Message{
		schema.UserMessage(rendered.Content),
	}

	result, err := a.chatModel.Generate(prompts.WithRenderedPrompt(ctx, rendered), messages)
	if err != nil {
		return "", fmt.Errorf("failed to refine generated cases: %w", err)
	}
	return result.Content, nil
}

func (a *Agent) GetType() string {
	return "DeepAgent"
}

func extractJSONPayload(raw string) string {
	trimmed := strings.TrimSpace(raw)
	if strings.HasPrefix(trimmed, "```") {
		lines := strings.Split(trimmed, "\n")
		if len(lines) > 0 && strings.HasPrefix(strings.TrimSpace(lines[0]), "```") {
			lines = lines[1:]
		}
		if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "```" {
			lines = lines[:len(lines)-1]
		}
		trimmed = strings.Join(lines, "\n")
	}

	trimmed = strings.TrimSpace(trimmed)
	start := strings.Index(trimmed, "[")
	end := strings.LastIndex(trimmed, "]")
	if start < 0 || end <= start {
		return ""
	}
	return strings.TrimSpace(trimmed[start : end+1])
}
