package deep

import (
	"context"
	"fmt"
	"strings"

	"caseagent/internal/agent/prompts"

	"github.com/cloudwego/eino/adk"
	"github.com/cloudwego/eino/components/model"
	"github.com/cloudwego/eino/schema"
)

type Agent struct {
	chatModel model.BaseChatModel
	subAgents []adk.Agent
	prompts   *prompts.Registry
}

type Config struct {
	ChatModel model.BaseChatModel
	SubAgents []adk.Agent
	Prompts   *prompts.Registry
}

func New(ctx context.Context, cfg *Config) (*Agent, error) {
	if cfg.ChatModel == nil {
		return nil, fmt.Errorf("chat model is required")
	}
	registry := cfg.Prompts
	if registry == nil {
		registry = prompts.DefaultRegistry()
	}

	return &Agent{
		chatModel: cfg.ChatModel,
		subAgents: cfg.SubAgents,
		prompts:   registry,
	}, nil
}

// GenerateCases generates sectioned test cases by coordinating sub-agents.
func (a *Agent) GenerateCases(ctx context.Context, requirements string, knowledge string) (string, error) {
	// For now, use the chat model directly to generate comprehensive test cases.
	// TODO: Implement full coordination with sub-agents.
	rendered, err := a.prompts.Render(prompts.DeepCases, prompts.CasePromptData{
		Requirements: requirements,
		Knowledge:    knowledge,
	})
	if err != nil {
		return "", err
	}

	messages := []*schema.Message{
		schema.UserMessage(rendered.Content),
	}

	result, err := a.chatModel.Generate(prompts.WithRenderedPrompt(ctx, rendered), messages)
	if err != nil {
		return "", fmt.Errorf("failed to generate test cases: %w", err)
	}

	return result.Content, nil
}

// RefineCases consolidates draft sections generated by sub-agents.
func (a *Agent) RefineCases(ctx context.Context, requirements string, knowledge string, draftJSON string) (string, error) {
	draftJSON = strings.TrimSpace(draftJSON)
	if draftJSON == "" {
		return "", fmt.Errorf("empty draft sections")
	}

	rendered, err := a.prompts.Render(prompts.DeepRefineCases, prompts.CasePromptData{
		Requirements: requirements,
		Knowledge:    knowledge,
		DraftJSON:    draftJSON,
	})
	if err != nil {
		return "", err
	}

	messages := []*schema.Message{
		schema.UserMessage(rendered.Content),
	}

	result, err := a.chatModel.Generate(prompts.WithRenderedPrompt(ctx, rendered), messages)
	if err != nil {
		return "", fmt.Errorf("failed to refine generated cases: %w", err)
	}
	return result.Content, nil
}

func (a *Agent) GetType() string {
	return "DeepAgent"
}
